### ISSUE TITLE
some tensorflow headers are no longer needed

### ISSUE THREAD

**Issue by advaitjain** [antmicro/tensorflow-arduino-examples#30]
This commit https://github.com/tensorflow/tensorflow/commit/4dadd1262353df4671b43f8275f3d03129bbb973 from https://github.com/tensorflow/tensorflow/pull/46438 removed the need for tensorflow/core/public/version.h and tensorflow/lite/version.h

These files can be removed from the arduino examples repo.

Tagging @PiotrZierhoffer

**Comment by PiotrZierhoffer** [comment]
Great catch. Reported this as an issue in our generator

**Comment by PiotrZierhoffer** [comment]
As mentioned in the linked issue, the generator is fixed and the latest PR I just merged has no version.h files.
